version: '2'
services:
  web:
    build: ./
    restart: always
    command: npm run start
    # command: sh -c "while true; do sleep 90; done;"
    volumes:
      - ./:/var/www/html
    ports:
     - "3001:3001"