version: '2'
services:
  web:
    build: ./
    restart: always
    command: npm run start
    volumes:
      - ./:/var/www/html
    ports:
     - "3001:3001"
    depends_on:
      - mongo
  mongo:
    build: ./mongo
    ports:
      - 27018:27017
    restart: always
    volumes:
      - ./datadb:/data/db